name: Build/Test/Release

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Versioning (${{github.run_number}})
      run: sed -i 's/PACKAGEVERSION/0.0.${{github.run_number}}/g' Directory.Build.props
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ./NtFreX.Precompiler/bin/Release/net6.0
    - name: Nuget Auth
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NtFreX/index.json"
    - name: Nuget Pack
      run: dotnet pack --configuration Release --no-build --output ./package -p:PackageVersion=0.0.${{github.run_number}}
    - name: Nuget Publish 
      run: dotnet nuget push "./package/NtFreX.Precompiler.0.0.${{github.run_number}}.nupkg" --source "github"
