name: Build/Test/Release

on:
  push:
    branches:
    - master
    
env:
  VERSION: '0.0.${{github.run_number}}-alpha'
  PACKAGE: 'NtFreX.Precompiler'
  TARGET: net6.0
   
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ./${{env.PACKAGE}}/bin/Release/${{env.TARGET}}
    - name: Nuget Auth
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{env.GITHUB_REPOSITORY_OWNER}}/index.json"
    - name: Nuget Pack
      run: dotnet pack --configuration Release --no-build --output ./package -p:PackageVersion=${{env.VERSION}}
    - name: Nuget Publish github
      run: dotnet nuget push "./package/${{env.PACKAGE}}.${{env.VERSION}}.nupkg" --source "github"
    - name: Nuget Publish
      run: dotnet nuget push "./package/${{env.PACKAGE}}.${{env.VERSION}}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
